define([
  'dojo/_base/declare',
  'dojo/Deferred'
],
function(
  declare,
  Deferred
)
{
  return declare([],
    {
        /*
          Assume all code in this file represents server side calls that you must wait to resolve
          Do not edit this file
        */
        lookupInventoryDetails: function(id)
        {
          var daPromise = new Deferred();
          var inventory = {"001": {"amountOnHand": 100, "salesRep": "123"},"002": {"amountOnHand": 9, "salesRep": "124"},"003": {"amountOnHand": 4, "salesRep": "125"},"004": {"amountOnHand": 20, "salesRep": "126"},"005": {"amountOnHand": 10, "salesRep": "127"}};
          var xmlHttpRequestResponse = inventory[id];
          daPromise.resolve(xmlHttpRequestResponse);
          return daPromise.promise;
        },
        lookupSalesRep: function(id)
        {
          var daPromise = new Deferred();
          var salesreps = {"123": {"name": "Super Man", "manager": "123"},"124": {"name": "Bat Man", "manager": "124"},"125": {"name": "Spider Man", "manager": "125"},"126": {"name": "Aqua Man", "manager": "126"},"127": {"name": "Iron Man", "manager": "127"}};
          var xmlHttpRequestResponse = salesreps[id];
          daPromise.resolve(xmlHttpRequestResponse);
          return daPromise.promise;
        },
        lookupManager: function(id)
        {
          var daPromise = new Deferred();
          var managers = {"123": {"name": "Jon Snow", "region": "123"},"124": {"name": "Robert Baratheon", "region": "124"},"125": {"name": "Balon Greyjoy", "region": "125"},"126": {"name": "Eddard Stark", "region": "126"},"127": {"name": "Tywin Lannister", "region": "127"}};
          var xmlHttpRequestResponse = managers[id];
          daPromise.resolve(xmlHttpRequestResponse);
          return daPromise.promise;
        },
        lookupRegion: function(id)
        {
          var daPromise = new Deferred();
          var region = {"123": {"name": "Northwest"}, "124": {"name": "Northeast"},"125": {"name": "Southwest"}, "126": {"name": "East"},"127": {"name": "West"}};
          var xmlHttpRequestResponse = region[id];
          daPromise.resolve(xmlHttpRequestResponse);
          return daPromise.promise;
        },
        lookupRegionAccounts: function(id)
        {
          var daPromise = new Deferred();
          var region = {"123": {"account": "0100"},"124": {"account": "0101"},"125": {"account": "0110"}, "126": {"account": "0111"},"127": {"account": "1000"}};
          var xmlHttpRequestResponse = region[id];
          daPromise.resolve(xmlHttpRequestResponse);
          return daPromise.promise;
        },
        lookupAccounts: function(id)
        {
          var daPromise = new Deferred();
          var accounts = {"0100": {"amount": 2000, "name": "Northwest fund"},"0101": {"amount": 1000, "name": "Northeast fund"},"0110": {"amount": 1500, "name": "Southwest fund"},"0111": {"amount": 2000, "name": "East fund"},"1000": {"amount": 1300, "name": "West fund"}};
          var xmlHttpRequestResponse = accounts[id];
          daPromise.resolve(xmlHttpRequestResponse);
          return daPromise.promise;
        }

    });
});
